name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liF6gVb6YsmP6rqn"
GITHUB_OWNER = "wackywoo5"
GITHUB_REPO = "navnboversea"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navnboversea.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navnboversea.pages.dev"

